version: "3.5"
services:
  postgres:
    image: postgres:14.3-alpine
    container_name: postgresdb
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: "chatdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Password"
      PG_DATA: ./snap/postgres/data/pgdata
#  rabbitmq:
#    image: rabbitmq:3.11.2-alpine
#    container_name: rabbitmq
#    ports:
#      - "61613:61613"
#    environment:
#      RABBITMQ_DEFAULT_USER: "guest"
#      RABBITMQ_DEFAULT_PASS: "guest"