version: "3.5"
services:
  postgres:
    image: postgres:14.3-alpine
    container_name: postgresdb
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: "chatdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Password"
      PG_DATA: ./snap/postgres/data/pgdata