apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatdb-deployment
  labels:
    app: chatdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatdb
  template:
    metadata:
      labels:
        app: chatdb
    spec:
      containers:
        - name: chatdb
          image: postgres:14.3-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: chatdb-secret
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chatdb-secret
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: chatdb-configmap
                  key: postgres-db
---
apiVersion: v1
kind: Service
metadata:
  name: chatdb-service
spec:
  selector:
    app: chatdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432