apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-kafka
  namespace: simplechat
data:
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-broker:9092"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
#  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  KAFKA_BROKER_ID: "1"
  KAFKA_CREATE_TOPICS: "EvgenKafkaCode"