apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo
  namespace: mongodb
data:
  baseUrl: https://cloud.mongodb.com

  # Optional Parameters
  # projectName: My Ops/Cloud Manager Project

#  orgId: 5ecd252f8c1a75033c74106c