apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb-database
          image: mongo:6.0.3
          resources:
            limits:
              cpu: 1
              memory: 0.5G
            requests:
              cpu: 1
              memory: 0.5G
