#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: configmap-mongodb
#  namespace: simplechat
#data:
#  SPRING_DATA_MONGODB_HOST: mongodb://mongodb:27017/chat_mongo
#  SPRING_DATA_MONGODB_PORT: 27017
#  SPRING_DATA_MONGODB_DATABASE: chat_mongo
#  SPRING_DATA_MONGODB_USERNAME: QWRtaW4=
  #  spring.data.mongodb.host: mongodb://mongodb:27017/chat_mongo
  #  spring.data.mongodb.port: 27017
#  spring.data.mongodb.database: chat_mongo
#  spring.data.mongodb.username: QWRtaW4=
  #Admin

  # Optional Parameters
  # projectName: My Ops/Cloud Manager Project

#  orgId: 5ecd252f8c1a75033c74106c